# Generated by Django 3.2.9 on 2021-11-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ability', models.CharField(choices=[('pedreiro', 'Pedreiro'), ('pintor', 'Pintor'), ('encacanador', 'Encanador')], max_length=100)),
            ],
        ),
    ]
